server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db224.dev.rs.com:3306/db_vr?useUnicode=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: user_vr
    password: user_vr20190411
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated # 生产者确认

mybatis-plus:
  type-aliases-package: com.somelogs.rabbitmq.producer.dal.entity
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      table-prefix: tb_